# Generated by Django 5.0.7 on 2025-02-18 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_alter_menuitem_category_and_more'),
        ('orders', '0003_remove_order_qr_code_alter_orderitem_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menuitem'),
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
